### ISSUE TITLE
Karlsruhe is not working for me anymore

### ISSUE THREAD

**Issue by riedel** [opacapp/opacapp-config-files#37]
I wonder if they changed the API. Can someone confirm that this  [api description](https://opac.karlsruhe.de/cgi-bin/koha/unapi) is still compliant to https://github.com/opacapp/opacapp-config-files/blob/1c1be40e24b11fb34410efe363a1979a9fe6cf27/bibs/Karlsruhe.json#L9

Unfortunately I could not find much more detailed info ad hoc on the different APIs.

**Comment by riedel** [comment]
[ "information": "http://www.karlsruhe.de/b2/bibliotheken/stadtbibliothek.de",](https://github.com/opacapp/opacapp-config-files/blob/1c1be40e24b11fb34410efe363a1979a9fe6cf27/bibs/Karlsruhe.json#L59)

needs to be changed too to: https://stadtbibliothek.karlsruhe.de/

**Comment by raphaelm** [comment]
They use an entirely different system now. The Opac App is discontinued, so we make no more changes.
